[package]
name = "mem_usage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wait4 = "0.1.3"

[profile.release]
opt-level = 3

[[bin]]
name = "mem"
path = "src/main.rs"
